title: GreenPill.pro
description: A Degen's guide to Zenon Network
show_downloads: false
google_analytics:
posthog_analytics: phc_uLCJA4LZw8f5eLpyHmRHVigcLSZQq4U1Q53jQXxKW6F
theme: jekyll-theme-hacker
